[package]
name = "burt-build"
version = "0.1.0"
edition = "2024"
default-run = "burt"

[[bin]]
name = "burt"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.31", features = ["derive"] }
nom = "8.0.0"
